export const collegeNameMap = new Map<string, string>([
    ["Miami (FL)", "Miami"],
    ["Western Ky.", "Western Kentucky"],
    ["Hawaii", "Hawai'i"],
    ["Southern Miss.", "Southern Mississippi"],
    ["UConn", "Connecticut"],
    ["Army West Point", "Army"],
    ["Central Mich.", "Central Michigan"],
    ["FIU", "Florida International"],
    ["UTSA", "UT San Antonio"],
    ["App State", "Appalachian State"],
    ["Ga. Southern", "Georgia Southern"],
    ["Southern California", "USC"],
    ["South Fla.", "South Florida"],
    ["Western Mich.", "Western Michigan"],
    ["Eastern Mich.", "Eastern Michigan"],
    ["Massachusetts", "UMass"],
    ["Sam Houston", "Sam Houston State"],
    ["Fla. Atlantic", "Florida Atlantic"],
    ["Charleston So.", "Charleston Southern"],
    ["Eastern Ky.", "Eastern Kentucky"],
    ["NIU", "Northern Illinois"],
    ["Alcorn", "Alcorn State"],
    ["Murray St.", "Murray State"],
    ["North Ala.", "North Alabama"],
    ["Southeastern La.", "Southeastern Louisiana"],
    ["ULM", "Louisiana Monroe"],
    ["UAlbany", "Albany"],
    ["LIU", "Long Island University"],
    ["West Ga.", "West Georgia"],
    ["Eastern Ill.", "Eastern Illinois"],
    ["San Jose St.", "San José State"],
    ["Northern Ariz.", "Northern Arizona"],
    ["Mississippi Val.", "Mississippi Valley State"],
    ["Lamar University", "Lamar"],
    ["Southeast Mo. St.", "Southeast Missouri State"],
    ["N.C. A&T", "North Carolina A&T"],
    ["Ark.-Pine Bluff", "Arkansas-Pine Bluff"],
    ["Middle Tenn.", "Middle Tennessee"]
]);